/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Clases.PaqueteTuristico;
import gestion.GestionPaquete;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CRISTOPHER
 */
public class frmMantenimientoPaquete extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private GestionPaquete gestionPaquete;
    
    /**
     * Creates new form frmMantenimientoPaquete
     */
    public frmMantenimientoPaquete() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Destino");
        modelo.addColumn("Duración (Días)");
        modelo.addColumn("Tipo");
        modelo.addColumn("Precio");
        modelo.addColumn("Cupo Máx.");
        modelo.addColumn("F. Salida");
        modelo.addColumn("F. Retorno");
        modelo.addColumn("Estado");
        tbPaquetes.setModel(modelo);
    }

    public frmMantenimientoPaquete(GestionPaquete gestionPaquete) {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Destino");
        modelo.addColumn("Duración (Días)");
        modelo.addColumn("Tipo");
        modelo.addColumn("Precio");
        modelo.addColumn("Cupo Máx.");
        modelo.addColumn("F. Salida");
        modelo.addColumn("F. Retorno");
        modelo.addColumn("Estado");
        tbPaquetes.setModel(modelo);
        
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.gestionPaquete = gestionPaquete;
        listarPaquetes();
    }

    void listarPaquetes() {
        modelo.setNumRows(0);
        for (int i = 0; i < gestionPaquete.obtenerTotalPaquetes(); i++) {
            PaqueteTuristico paq = gestionPaquete.obtenerPaquete(i);
            
            Object[] fila = new Object[11];
            fila[0] = paq.getCodigo();
            fila[1] = paq.getNombre();
            fila[2] = paq.getDestino();
            fila[3] = paq.getDuracionDias();
            fila[4] = paq.getTipo();
            fila[5] = paq.getPrecioPorPersona();
            fila[6] = paq.getCupoMaximo();
            fila[7] = paq.getFechaSalida();
            fila[8] = paq.getFechaRetorno();
            fila[9] = paq.getEstado();
            
            modelo.addRow(fila);
        }
    }

    private void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDestino.setText("");
        txtDuracion.setText("");
        txtTipo.setText("");
        txtPrecio.setText("");
        txtCupoMaximo.setText("");
        txtFechaSalida.setText("");
        txtFechaRetorno.setText("");
        txtEstado.setText("");
        txtCodigo.setEditable(true);
        txtCodigo.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPaquetes = new javax.swing.JTable();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblDuracionDias = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        lblFechaRetorno = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtCupoMaximo = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();
        txtFechaRetorno = new javax.swing.JTextField();
        lblCupoMaximo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblPrecioPorPersona = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tbPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbPaquetes);

        lblCodigo.setText("Codigo");

        lblNombre.setText("Nombre");

        lblDestino.setText("Destino");

        lblDuracionDias.setText("Duracion Dias");

        lblTipo.setText("Tipo");

        lblFechaSalida.setText("Fecha Salida");

        lblFechaRetorno.setText("Fecha Retorno");

        lblCupoMaximo.setText("Cupo Maximo");

        lblEstado.setText("Estado");

        lblPrecioPorPersona.setText("Precio por Persona");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(txtFechaRetorno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFechaSalida, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCupoMaximo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDuracion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDestino, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addComponent(lblFechaRetorno)
                            .addComponent(lblFechaSalida)
                            .addComponent(lblCupoMaximo)
                            .addComponent(lblTipo)
                            .addComponent(lblDuracionDias)
                            .addComponent(lblDestino)
                            .addComponent(lblNombre)
                            .addComponent(lblCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar))
                            .addComponent(lblPrecioPorPersona))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuracionDias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioPorPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCupoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCupoMaximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaRetorno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnBuscar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        String destino = txtDestino.getText().trim();
        int duracion = Integer.parseInt(txtDuracion.getText().trim());
        String tipo = txtTipo.getText().trim();
        double precio = Double.parseDouble(txtPrecio.getText().trim());
        int cupoMaximo = Integer.parseInt(txtCupoMaximo.getText().trim());
        String fechaSalida = txtFechaSalida.getText().trim();
        String fechaRetorno = txtFechaRetorno.getText().trim();
        String estado = txtEstado.getText().trim();

        if (codigo.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Código y Nombre son obligatorios.");
            return;
        }

       
        PaqueteTuristico nuevoPaquete = new PaqueteTuristico(codigo, nombre, destino, duracion, tipo, precio, cupoMaximo, fechaSalida, fechaRetorno, estado);

        if (gestionPaquete.registrar(nuevoPaquete)) {
            JOptionPane.showMessageDialog(this, "Paquete registrado con éxito.");
            listarPaquetes();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error: El código ya existe o no hay espacio.");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codigoBuscar = txtCodigo.getText().trim();

        if (codigoBuscar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un código para buscar.");
            return;
        }

        PaqueteTuristico encontrado = gestionPaquete.buscarPorCodigo(codigoBuscar);

        if (encontrado != null) {
            txtNombre.setText(encontrado.getNombre());
            txtDestino.setText(encontrado.getDestino());
            txtDuracion.setText(String.valueOf(encontrado.getDuracionDias()));
            txtTipo.setText(encontrado.getTipo());
            txtPrecio.setText(String.valueOf(encontrado.getPrecioPorPersona()));
            txtCupoMaximo.setText(String.valueOf(encontrado.getCupoMaximo()));
            txtFechaSalida.setText(encontrado.getFechaSalida());
            txtFechaRetorno.setText(encontrado.getFechaRetorno());
            txtEstado.setText(encontrado.getEstado());
            txtCodigo.setEditable(false);
        } else {
            JOptionPane.showMessageDialog(this, "Paquete no encontrado.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        String destino = txtDestino.getText().trim();
        int duracion = Integer.parseInt(txtDuracion.getText().trim());
        String tipo = txtTipo.getText().trim();
        double precio = Double.parseDouble(txtPrecio.getText().trim());
        int cupoMaximo = Integer.parseInt(txtCupoMaximo.getText().trim());
        String fechaSalida = txtFechaSalida.getText().trim();
        String fechaRetorno = txtFechaRetorno.getText().trim();
        String estado = txtEstado.getText().trim();

        PaqueteTuristico paqActualizar = new PaqueteTuristico(codigo, nombre, destino, duracion, tipo, precio, cupoMaximo, fechaSalida, fechaRetorno, estado);

        if (gestionPaquete.actualizar(paqActualizar)) {
            JOptionPane.showMessageDialog(this, "Paquete actualizado con éxito.");
            listarPaquetes();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar. Verifique el código.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText().trim();

        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el código del paquete a eliminar.");
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro de eliminar este paquete?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            if (gestionPaquete.eliminar(codigo)) {
                JOptionPane.showMessageDialog(this, "Paquete eliminado.");
                listarPaquetes();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el paquete.");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimientoPaquete(new gestion.GestionPaquete()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCupoMaximo;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblDuracionDias;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaRetorno;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioPorPersona;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tbPaquetes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCupoMaximo;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaRetorno;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
