/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Clases.Empleado;
import gestion.*;
import javax.swing.UIManager;
import utilitario.EscritorioPersonalizado;

/**
 *
 * @author np192
 */
public class frmPrincipal extends javax.swing.JFrame {

    private GestionEmpleado gestionEmpleado = new GestionEmpleado();
    private GestionCliente gestionCliente = new GestionCliente();
    private GestionDestino gestionDestino = new GestionDestino();
    private GestionPaquete gestionPaquete = new GestionPaquete();
    private GestionReserva gestionReserva = new GestionReserva();
    private GestionPromocion agendaPromociones = new gestion.GestionPromocion();
    
    private Empleado empleadoLogueado;
    private EscritorioPersonalizado escritorio; 

    public frmPrincipal(Empleado empleado) {
        initComponents();
        
        escritorio = new EscritorioPersonalizado(); 
        this.setContentPane(escritorio);
        
        this.empleadoLogueado = empleado;
               
        cargarPermisos();
    }
    
    private void cargarPermisos() {
        String rol = empleadoLogueado.getRol();
        
        if (rol.equals("Administrador")) {
            mnMantenimiento.setVisible(true);
            mnOperaciones.setVisible(false);
            mnConsultas.setVisible(true);
        } else if (rol.equals("Asesor de Viaje")) {
            mnMantenimiento.setVisible(false);
            mnOperaciones.setVisible(true);
            mnConsultas.setVisible(true);
        } else if (rol.equals("Operador")) {
            mnMantenimiento.setVisible(false);
            mnOperaciones.setVisible(false);
            mnConsultas.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMantenimiento = new javax.swing.JMenu();
        mnitmEmpleados = new javax.swing.JMenuItem();
        mnitmDestinos = new javax.swing.JMenuItem();
        mnitmPaquetes = new javax.swing.JMenuItem();
        mnitmPromociones = new javax.swing.JMenuItem();
        mnOperaciones = new javax.swing.JMenu();
        mnitmReservas = new javax.swing.JMenuItem();
        mnitmPagos = new javax.swing.JMenuItem();
        mnitmClientes = new javax.swing.JMenuItem();
        mnitmDetallesPaquete = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        mnitmReportesAgencia = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/949890.png"))); // NOI18N
        mnMantenimiento.setText("Mantenimiento");

        mnitmEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        mnitmEmpleados.setText("Empleados");
        mnitmEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmEmpleadosActionPerformed(evt);
            }
        });
        mnMantenimiento.add(mnitmEmpleados);

        mnitmDestinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4668400.png"))); // NOI18N
        mnitmDestinos.setText("Destinos");
        mnitmDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmDestinosActionPerformed(evt);
            }
        });
        mnMantenimiento.add(mnitmDestinos);

        mnitmPaquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1554561.png"))); // NOI18N
        mnitmPaquetes.setText("Paquetes");
        mnitmPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmPaquetesActionPerformed(evt);
            }
        });
        mnMantenimiento.add(mnitmPaquetes);

        mnitmPromociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/372754.png"))); // NOI18N
        mnitmPromociones.setText("Promociones");
        mnitmPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmPromocionesActionPerformed(evt);
            }
        });
        mnMantenimiento.add(mnitmPromociones);

        jMenuBar1.add(mnMantenimiento);

        mnOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8759049.png"))); // NOI18N
        mnOperaciones.setText("Operaciones");

        mnitmReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        mnitmReservas.setText("Reservas");
        mnitmReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmReservasActionPerformed(evt);
            }
        });
        mnOperaciones.add(mnitmReservas);

        mnitmPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagos.png"))); // NOI18N
        mnitmPagos.setText("Pagos");
        mnitmPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmPagosActionPerformed(evt);
            }
        });
        mnOperaciones.add(mnitmPagos);

        mnitmClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        mnitmClientes.setText("Clientes");
        mnitmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmClientesActionPerformed(evt);
            }
        });
        mnOperaciones.add(mnitmClientes);

        mnitmDetallesPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1554561.png"))); // NOI18N
        mnitmDetallesPaquete.setText("Detalles Paquete");
        mnitmDetallesPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmDetallesPaqueteActionPerformed(evt);
            }
        });
        mnOperaciones.add(mnitmDetallesPaquete);

        jMenuBar1.add(mnOperaciones);

        mnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1022319.png"))); // NOI18N
        mnConsultas.setText("Consultas");

        mnitmReportesAgencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        mnitmReportesAgencia.setText("Reportes Agencia");
        mnitmReportesAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmReportesAgenciaActionPerformed(evt);
            }
        });
        mnConsultas.add(mnitmReportesAgencia);

        jMenuBar1.add(mnConsultas);

        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerrar.png"))); // NOI18N
        mnSalir.setText("Salir");
        mnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitmEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmEmpleadosActionPerformed
        // TODO add your handling code here:
        frmMantenimientoEmpleado ventana = new frmMantenimientoEmpleado(gestionEmpleado);
        ventana.setLocationRelativeTo(null); 
        ventana.setVisible(true);
    }//GEN-LAST:event_mnitmEmpleadosActionPerformed

    private void mnitmDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmDestinosActionPerformed
        // TODO add your handling code here:
        frmMantenimientoDestino ventanaDestino = new frmMantenimientoDestino(this.gestionDestino);
        ventanaDestino.setLocationRelativeTo(null); 
        ventanaDestino.setVisible(true); 
    }//GEN-LAST:event_mnitmDestinosActionPerformed

    private void mnitmPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmPaquetesActionPerformed
        // TODO add your handling code here:
        frmMantenimientoPaquete ventanaPaquete = new frmMantenimientoPaquete(this.gestionPaquete);
        ventanaPaquete.setLocationRelativeTo(null);
        ventanaPaquete.setVisible(true);
    }//GEN-LAST:event_mnitmPaquetesActionPerformed

    private void mnitmReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmReservasActionPerformed
        // TODO add your handling code here:
        frmRegistroReserva ventanaReserva = new frmRegistroReserva(this.gestionReserva, this.gestionPaquete, this.gestionCliente);
        ventanaReserva.setLocationRelativeTo(null);
        ventanaReserva.setVisible(true);
    }//GEN-LAST:event_mnitmReservasActionPerformed

    private void mnitmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmClientesActionPerformed
        // TODO add your handling code here:
        frmMantenimientoCliente ventanaCliente = new frmMantenimientoCliente(this.gestionCliente);
        ventanaCliente.setLocationRelativeTo(null);
        ventanaCliente.setVisible(true);
    }//GEN-LAST:event_mnitmClientesActionPerformed

    private void mnitmPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmPagosActionPerformed
        // TODO add your handling code here:
        frmRegistroPagos ventanaPagos = new frmRegistroPagos(this.gestionReserva);
        ventanaPagos.setLocationRelativeTo(null);
        ventanaPagos.setVisible(true);
    }//GEN-LAST:event_mnitmPagosActionPerformed

    private void mnitmDetallesPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmDetallesPaqueteActionPerformed
        // TODO add your handling code here:
        frmDetallePaquete ventanaDetalle = new frmDetallePaquete(this.gestionPaquete);
        ventanaDetalle.setLocationRelativeTo(null);
        ventanaDetalle.setVisible(true);
    }//GEN-LAST:event_mnitmDetallesPaqueteActionPerformed

    private void mnitmReportesAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmReportesAgenciaActionPerformed
        // TODO add your handling code here:
        frmReportesAgencia ventanaReportes = new frmReportesAgencia(this.gestionReserva, this.gestionPaquete);
        ventanaReportes.setLocationRelativeTo(null);
        ventanaReportes.setVisible(true);
    }//GEN-LAST:event_mnitmReportesAgenciaActionPerformed

    private void mnitmPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmPromocionesActionPerformed
        // TODO add your handling code here:
        frmMantenimientoPromocion ventanaPromo = new frmMantenimientoPromocion(this.agendaPromociones);
        ventanaPromo.setLocationRelativeTo(null);
        ventanaPromo.setVisible(true);
    }//GEN-LAST:event_mnitmPromocionesActionPerformed

    private void mnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Clases.Empleado empleadoPrueba = new Clases.Empleado("admin", "123456", "Administrador", "00000000", "Admin", "Prueba");
            new frmPrincipal(empleadoPrueba).setVisible(true);
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnMantenimiento;
    private javax.swing.JMenu mnOperaciones;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenuItem mnitmClientes;
    private javax.swing.JMenuItem mnitmDestinos;
    private javax.swing.JMenuItem mnitmDetallesPaquete;
    private javax.swing.JMenuItem mnitmEmpleados;
    private javax.swing.JMenuItem mnitmPagos;
    private javax.swing.JMenuItem mnitmPaquetes;
    private javax.swing.JMenuItem mnitmPromociones;
    private javax.swing.JMenuItem mnitmReportesAgencia;
    private javax.swing.JMenuItem mnitmReservas;
    // End of variables declaration//GEN-END:variables
}
