/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Clases.Reserva;
import Clases.PaqueteTuristico;
import gestion.GestionReserva;
import gestion.GestionPaquete;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CRISTOPHER
 */
public class frmReportesAgencia extends javax.swing.JFrame {

    private DefaultTableModel modReservasPaq;
    private DefaultTableModel modPendientes;
    private DefaultTableModel modDestinos;
    private DefaultTableModel modIngresos;
    
    private GestionReserva gestionReserva;
    private GestionPaquete gestionPaquete;
    
    /**
     * Creates new form frmReportesAgencia
     */
    public frmReportesAgencia() {
        initComponents();
        inicializarModelos();
    }

    public frmReportesAgencia(GestionReserva gestionReserva, GestionPaquete gestionPaquete) {
        initComponents();
        this.gestionReserva = gestionReserva;
        this.gestionPaquete = gestionPaquete;

        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        inicializarModelos();
    }

    private void inicializarModelos() {
        modReservasPaq = new DefaultTableModel();
        modReservasPaq.addColumn("Cod. Reserva");
        modReservasPaq.addColumn("Adultos");
        modReservasPaq.addColumn("Menores");
        modReservasPaq.addColumn("Precio Total");
        modReservasPaq.addColumn("Estado");
        tbReporteReservasPaq.setModel(modReservasPaq);

        modPendientes = new DefaultTableModel();
        modPendientes.addColumn("Cod. Reserva");
        modPendientes.addColumn("Paquete");
        modPendientes.addColumn("Total S/.");
        modPendientes.addColumn("Abonado S/.");
        modPendientes.addColumn("Saldo Pendiente");
        tbReportePendientes.setModel(modPendientes);


        modDestinos = new DefaultTableModel();
        modDestinos.addColumn("Destino Turístico");
        modDestinos.addColumn("Veces Solicitado");
        tbDestinosSolicitados.setModel(modDestinos);

        modIngresos = new DefaultTableModel();
        modIngresos.addColumn("Concepto Comercial");
        modIngresos.addColumn("Monto Total S/.");
        tbIngresosGenerales.setModel(modIngresos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlReservasPaquete = new javax.swing.JPanel();
        txtFiltroCodigoPaquete = new javax.swing.JTextField();
        lblFiltroCodigoPaquete = new javax.swing.JLabel();
        btnBuscarReservasPaq = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReporteReservasPaq = new javax.swing.JTable();
        pnlSaldosPendientes = new javax.swing.JPanel();
        btnCargarPendientes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbReportePendientes = new javax.swing.JTable();
        pnlEstadisticas = new javax.swing.JPanel();
        btnCalcularEstadisticas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDestinosSolicitados = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbIngresosGenerales = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFiltroCodigoPaquete.setText("Filtro Codigo Paquete");

        btnBuscarReservasPaq.setText("Buscar Reservas Paq");
        btnBuscarReservasPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservasPaqActionPerformed(evt);
            }
        });

        tbReporteReservasPaq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbReporteReservasPaq);

        javax.swing.GroupLayout pnlReservasPaqueteLayout = new javax.swing.GroupLayout(pnlReservasPaquete);
        pnlReservasPaquete.setLayout(pnlReservasPaqueteLayout);
        pnlReservasPaqueteLayout.setHorizontalGroup(
            pnlReservasPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservasPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReservasPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservasPaqueteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlReservasPaqueteLayout.createSequentialGroup()
                        .addComponent(txtFiltroCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFiltroCodigoPaquete)
                        .addGap(21, 21, 21)
                        .addComponent(btnBuscarReservasPaq)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReservasPaqueteLayout.setVerticalGroup(
            pnlReservasPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservasPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReservasPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltroCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFiltroCodigoPaquete)
                    .addComponent(btnBuscarReservasPaq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reservas por Paquete", pnlReservasPaquete);

        btnCargarPendientes.setText("Cargar Pendientes");
        btnCargarPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarPendientesActionPerformed(evt);
            }
        });

        tbReportePendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbReportePendientes);

        javax.swing.GroupLayout pnlSaldosPendientesLayout = new javax.swing.GroupLayout(pnlSaldosPendientes);
        pnlSaldosPendientes.setLayout(pnlSaldosPendientesLayout);
        pnlSaldosPendientesLayout.setHorizontalGroup(
            pnlSaldosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaldosPendientesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlSaldosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlSaldosPendientesLayout.setVerticalGroup(
            pnlSaldosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaldosPendientesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCargarPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Saldos y Pendientes", pnlSaldosPendientes);

        btnCalcularEstadisticas.setText("Calcular Estadisticas");
        btnCalcularEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEstadisticasActionPerformed(evt);
            }
        });

        tbDestinosSolicitados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbDestinosSolicitados);

        tbIngresosGenerales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbIngresosGenerales);

        javax.swing.GroupLayout pnlEstadisticasLayout = new javax.swing.GroupLayout(pnlEstadisticas);
        pnlEstadisticas.setLayout(pnlEstadisticasLayout);
        pnlEstadisticasLayout.setHorizontalGroup(
            pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                        .addComponent(btnCalcularEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(263, Short.MAX_VALUE))
                    .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        pnlEstadisticasLayout.setVerticalGroup(
            pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCalcularEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Estadísticas Generales", pnlEstadisticas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarReservasPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservasPaqActionPerformed
        // TODO add your handling code here:
        String codBuscar = txtFiltroCodigoPaquete.getText().trim();
        if (codBuscar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, digite un código de paquete turístico.");
            return;
        }

        modReservasPaq.setNumRows(0);
        int contador = 0;

        for (int i = 0; i < gestionReserva.obtenerTotalReservas(); i++) {
            Reserva res = gestionReserva.obtenerReserva(i);
            if (res.getPaquete() != null && res.getPaquete().getCodigo().equalsIgnoreCase(codBuscar)) {
                Object[] fila = new Object[5];
                fila[0] = res.getCodigoReserva();
                fila[1] = res.getPasajerosAdultos();
                fila[2] = res.getPasajerosMenores();
                fila[3] = res.getPrecioTotal();
                fila[4] = res.getEstadoReserva();
                modReservasPaq.addRow(fila);
                contador++;
            }
        }
    
        if (contador == 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron reservas para el paquete: " + codBuscar);
        }
    }//GEN-LAST:event_btnBuscarReservasPaqActionPerformed

    private void btnCargarPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPendientesActionPerformed
        // TODO add your handling code here:
        modPendientes.setNumRows(0);
        int deudores = 0;
    
        for (int i = 0; i < gestionReserva.obtenerTotalReservas(); i++) {
            Reserva res = gestionReserva.obtenerReserva(i);

            if (res.saldoPendiente() > 0) {
                Object[] fila = new Object[5];
                fila[0] = res.getCodigoReserva();
                fila[1] = (res.getPaquete() != null) ? res.getPaquete().getNombre() : "N/A";
                fila[2] = res.getPrecioTotal();
                fila[3] = res.pagoHecho();
                fila[4] = res.saldoPendiente();
                modPendientes.addRow(fila);
                deudores++;
            }
        }
    
        if (deudores == 0) {
            JOptionPane.showMessageDialog(this, "¡Excelente! No hay clientes con saldos pendientes por pagar.");
        }
    }//GEN-LAST:event_btnCargarPendientesActionPerformed

    private void btnCalcularEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEstadisticasActionPerformed
        // TODO add your handling code here:
        modDestinos.setNumRows(0);
        modIngresos.setNumRows(0);

        double ingresosTotalesRecaudados = 0;
        double facturacionPotencialTotal = 0;

        for (int i = 0; i < gestionReserva.obtenerTotalReservas(); i++) {
            Reserva res = gestionReserva.obtenerReserva(i);
            ingresosTotalesRecaudados += res.pagoHecho();
            facturacionPotencialTotal += res.getPrecioTotal();
        }

        modIngresos.addRow(new Object[]{"Ingresos Reales en Caja (Cuotas Cobradas)", ingresosTotalesRecaudados});
        modIngresos.addRow(new Object[]{"Monto Total de Ventas Registradas", facturacionPotencialTotal});
        modIngresos.addRow(new Object[]{"Cuentas por Cobrar (Saldos por Liquidar)", facturacionPotencialTotal - ingresosTotalesRecaudados});

        for (int i = 0; i < gestionPaquete.obtenerTotalPaquetes(); i++) {
            PaqueteTuristico paq = gestionPaquete.obtenerPaquete(i);
            int cantidadReservasAsociadas = 0;

            for (int j = 0; j < gestionReserva.obtenerTotalReservas(); j++) {
                Reserva res = gestionReserva.obtenerReserva(j);
                if (res.getPaquete() != null && res.getPaquete().getCodigo().equalsIgnoreCase(paq.getCodigo())) {
                    cantidadReservasAsociadas++;
                }
            }
        
            if (cantidadReservasAsociadas > 0) {
                modDestinos.addRow(new Object[]{paq.getNombre(), cantidadReservasAsociadas});
            }
        }
    }//GEN-LAST:event_btnCalcularEstadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportesAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportesAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportesAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportesAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportesAgencia(new gestion.GestionReserva(), new gestion.GestionPaquete()).setVisible(true);}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarReservasPaq;
    private javax.swing.JButton btnCalcularEstadisticas;
    private javax.swing.JButton btnCargarPendientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblFiltroCodigoPaquete;
    private javax.swing.JPanel pnlEstadisticas;
    private javax.swing.JPanel pnlReservasPaquete;
    private javax.swing.JPanel pnlSaldosPendientes;
    private javax.swing.JTable tbDestinosSolicitados;
    private javax.swing.JTable tbIngresosGenerales;
    private javax.swing.JTable tbReportePendientes;
    private javax.swing.JTable tbReporteReservasPaq;
    private javax.swing.JTextField txtFiltroCodigoPaquete;
    // End of variables declaration//GEN-END:variables
}
