/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Clases.Reserva;
import Clases.Pago;
import gestion.GestionReserva;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTOPHER
 */
public class frmRegistroPagos extends javax.swing.JFrame {

    private GestionReserva gestionReserva;
    /**
     * Creates new form frmRegistroPagos
     */
    public frmRegistroPagos() {
        initComponents();
    }

    public frmRegistroPagos(GestionReserva gestionReserva) {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.gestionReserva = gestionReserva;
        
        txtPrecioTotal.setEditable(false);
        txtMontoAbonado.setEditable(false);
        txtSaldoPendiente.setEditable(false);
    }

    private void limpiarCampos() {
        txtCodigoReserva.setText("");
        txtMontoPago.setText("");
        txtPrecioTotal.setText("");
        txtMontoAbonado.setText("");
        txtSaldoPendiente.setText("");
        cboMetodoPago.setSelectedIndex(0);
        txtCodigoReserva.setEditable(true);
        txtCodigoReserva.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoReserva = new javax.swing.JTextField();
        txtMontoPago = new javax.swing.JTextField();
        cboMetodoPago = new javax.swing.JComboBox<>();
        btnBuscarReserva = new javax.swing.JButton();
        btnRegistrarPago = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtPrecioTotal = new javax.swing.JTextField();
        txtMontoAbonado = new javax.swing.JTextField();
        txtSaldoPendiente = new javax.swing.JTextField();
        lblPrecioTotal = new javax.swing.JLabel();
        lblMontoAbonado = new javax.swing.JLabel();
        lblSaldoPendiente = new javax.swing.JLabel();
        lblCodigoReserva = new javax.swing.JLabel();
        lblMontoPago = new javax.swing.JLabel();
        lblMetodoPago = new javax.swing.JLabel();
        btnMostrarDolares = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Transferencia" }));

        btnBuscarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1022319.png"))); // NOI18N
        btnBuscarReserva.setText("Buscar Reserva");
        btnBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservaActionPerformed(evt);
            }
        });

        btnRegistrarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vcsnormal.png"))); // NOI18N
        btnRegistrarPago.setText("Registrar Pago");
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/419660.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtPrecioTotal.setEditable(false);

        txtMontoAbonado.setEditable(false);

        txtSaldoPendiente.setEditable(false);

        lblPrecioTotal.setText("Precio Total");

        lblMontoAbonado.setText("Monto Abonado");

        lblSaldoPendiente.setText("Saldo Pendiente");

        lblCodigoReserva.setText("Codigo Reserva");

        lblMontoPago.setText("Monto Pago");

        lblMetodoPago.setText("Metodo Pago");

        btnMostrarDolares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/64054-united-symbol-dollar-sign-states-currency-icon (1).png"))); // NOI18N
        btnMostrarDolares.setText("Mostrar en dolares");
        btnMostrarDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDolaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMetodoPago)
                                .addGap(55, 55, 55)
                                .addComponent(cboMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoReserva)
                                    .addComponent(lblMontoPago))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMontoAbonado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontoAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSaldoPendiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSaldoPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrecioTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarDolares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioTotal)
                    .addComponent(lblCodigoReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoAbonado)
                    .addComponent(lblMontoPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldoPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoPendiente)
                    .addComponent(lblMetodoPago))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarReserva)
                    .addComponent(btnRegistrarPago)
                    .addComponent(btnLimpiar))
                .addGap(50, 50, 50)
                .addComponent(btnMostrarDolares)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservaActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoReserva.getText().trim();

    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el código de la reserva a buscar.");
        return;
    }

    Reserva res = gestionReserva.buscarPorCodigo(codigo);

    if (res != null) {
        txtPrecioTotal.setText(String.valueOf(res.getPrecioTotal()));
        txtMontoAbonado.setText(String.valueOf(res.pagoHecho()));
        txtSaldoPendiente.setText(String.valueOf(res.saldoPendiente()));
        txtCodigoReserva.setEditable(false);
    } else {
        JOptionPane.showMessageDialog(this, "Reserva no encontrada.");
    }
    }//GEN-LAST:event_btnBuscarReservaActionPerformed

    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoReserva.getText().trim();
        String montoStr = txtMontoPago.getText().trim();

        if (codigo.isEmpty() || montoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe buscar una reserva e ingresar un monto a pagar.");
            return;
        }

        Reserva res = gestionReserva.buscarPorCodigo(codigo);
        if (res == null) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar una reserva válida.");
            return;
        }

        double monto = Double.parseDouble(montoStr);
        String metodo = cboMetodoPago.getSelectedItem().toString();

        if (monto <= 0) {
            JOptionPane.showMessageDialog(this, "El monto a pagar debe ser mayor a cero.");
            return;
        }

        if (monto > res.saldoPendiente()) {
            JOptionPane.showMessageDialog(this, "Error: El monto ingresado supera al saldo pendiente (" + res.saldoPendiente() + ").");
            return;
        }

        java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String fechaActual = java.time.LocalDate.now().format(dtf);

        Pago nuevoPago = new Pago(res, monto, metodo, fechaActual);

        if (gestionReserva.registrarNuevoPago(codigo, nuevoPago)) {
        
        txtMontoAbonado.setText(String.valueOf(res.pagoHecho()));
        txtSaldoPendiente.setText(String.valueOf(res.saldoPendiente()));
        
        JOptionPane.showMessageDialog(this, "¡Pago registrado correctamente! Estado de la Reserva: " + res.getEstadoReserva());

        String voucher = "========================================\n"
                       + "             VOUCHER DE RESERVA         \n"
                       + "========================================\n"
                       + "Código de Reserva: " + res.getCodigoReserva() + "\n"
                       + "Paquete: " + (res.getPaquete() != null ? res.getPaquete().getNombre() : "N/A") + "\n"
                       + "Fecha de Salida: " + (res.getPaquete() != null ? res.getPaquete().getFechaSalida() : "N/A") + "\n"
                       + "Fecha de Retorno: " + (res.getPaquete() != null ? res.getPaquete().getFechaRetorno() : "N/A") + "\n"
                       + "----------------------------------------\n"
                       + "Pasajeros Adultos: " + res.getPasajerosAdultos() + "\n"
                       + "Pasajeros Menores: " + res.getPasajerosMenores() + "\n"
                       + "----------------------------------------\n"
                       + "PRECIO TOTAL:    S/. " + res.getPrecioTotal() + "\n"
                       + "MONTO ABONADO:   S/. " + res.pagoHecho() + "\n"
                       + "SALDO PENDIENTE: S/. " + res.saldoPendiente() + "\n"
                       + "ÚLTIMO PAGO:     S/. " + monto + " (" + fechaActual + ")\n"
                       + "MÉTODO DE PAGO:  " + metodo + "\n"
                       + "ESTADO ACTUAL:   " + res.getEstadoReserva().toUpperCase() + "\n"
                       + "========================================\n"
                       + "          ¡Gracias por su compra!       \n"
                       + "========================================";
                       
            JOptionPane.showMessageDialog(this, voucher, "Comprobante de Reserva - Req 9", JOptionPane.INFORMATION_MESSAGE);
        
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar el pago. Es posible que haya alcanzado el límite máximo de 4 cuotas.");
        }
    }//GEN-LAST:event_btnRegistrarPagoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMostrarDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDolaresActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoReserva.getText().trim();
        Reserva res = gestionReserva.buscarPorCodigo(codigo);

    if (res != null) {
        txtPrecioTotal.setText(String.valueOf(res.getPrecioTotal()*0.29));
        txtMontoAbonado.setText(String.valueOf(res.pagoHecho()*0.29));
        txtSaldoPendiente.setText(String.valueOf(res.saldoPendiente()*0.29));
        txtCodigoReserva.setEditable(false);
    }
        
    }//GEN-LAST:event_btnMostrarDolaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroPagos(new gestion.GestionReserva()).setVisible(true);}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarReserva;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarDolares;
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JComboBox<String> cboMetodoPago;
    private javax.swing.JLabel lblCodigoReserva;
    private javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblMontoAbonado;
    private javax.swing.JLabel lblMontoPago;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblSaldoPendiente;
    private javax.swing.JTextField txtCodigoReserva;
    private javax.swing.JTextField txtMontoAbonado;
    private javax.swing.JTextField txtMontoPago;
    private javax.swing.JTextField txtPrecioTotal;
    private javax.swing.JTextField txtSaldoPendiente;
    // End of variables declaration//GEN-END:variables
}
