/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Clases.PaqueteTuristico;
import gestion.GestionPaquete;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTOPHER
 */
public class frmDetallePaquete extends javax.swing.JFrame {

    private GestionPaquete gestionPaquete;
    
    /**
     * Creates new form frmDetallePaquete
     */
    public frmDetallePaquete() {
        initComponents();
    }

    public frmDetallePaquete(GestionPaquete gestionPaquete) {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.gestionPaquete = gestionPaquete;
    }

    private void limpiarCampos() {
        txtCodigoPaquete.setText("");
        txtServicios.setText("");
        txtItinerario.setText("");
        txtCodigoPaquete.setEditable(true);
        txtCodigoPaquete.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        txtCodigoPaquete = new javax.swing.JTextField();
        lblCodigoPaquete = new javax.swing.JLabel();
        btnBuscarPaquete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtServicios = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtItinerario = new javax.swing.JTextArea();
        btnGuardarDetalles = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblItinerario = new javax.swing.JLabel();
        lblServicios1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCodigoPaquete.setText("Codigo Paquete");

        btnBuscarPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1022319.png"))); // NOI18N
        btnBuscarPaquete.setText("Buscar Paquete");
        btnBuscarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPaqueteActionPerformed(evt);
            }
        });

        txtServicios.setColumns(20);
        txtServicios.setRows(5);
        jScrollPane1.setViewportView(txtServicios);

        txtItinerario.setColumns(20);
        txtItinerario.setRows(5);
        jScrollPane2.setViewportView(txtItinerario);

        btnGuardarDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4856668.png"))); // NOI18N
        btnGuardarDetalles.setText("Guardar Detalles");
        btnGuardarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDetallesActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/419660.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblItinerario.setText("ITINERARIO");

        lblServicios1.setText("SERVICIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCodigoPaquete))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblServicios1)
                                    .addComponent(btnBuscarPaquete))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(btnGuardarDetalles)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnLimpiar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(199, 199, 199)
                                        .addComponent(lblItinerario)
                                        .addGap(67, 67, 67)))))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoPaquete))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarDetalles)
                    .addComponent(btnBuscarPaquete)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServicios1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPaqueteActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoPaquete.getText().trim();

        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un código de paquete.");
            return;
        }

        PaqueteTuristico paq = gestionPaquete.buscarPorCodigo(codigo);

        if (paq != null) {
            txtServicios.setText(paq.getServiciosIncluidos());
            txtItinerario.setText(paq.getItinerarioDias());
            txtCodigoPaquete.setEditable(false);
            JOptionPane.showMessageDialog(this, "Paquete '" + paq.getNombre() + "' cargado con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "El código de paquete ingresado no existe.");
        }
    }//GEN-LAST:event_btnBuscarPaqueteActionPerformed

    private void btnGuardarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDetallesActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoPaquete.getText().trim();

        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar y cargar un paquete válido.");
            return;
        }

        PaqueteTuristico paq = gestionPaquete.buscarPorCodigo(codigo);
        if (paq != null) {
            String servicios = txtServicios.getText().trim();
            String itinerario = txtItinerario.getText().trim();
        
            paq.setServiciosIncluidos(servicios);
            paq.setItinerarioDias(itinerario);
        
            JOptionPane.showMessageDialog(this, "¡Servicios e Itinerario guardados correctamente para el paquete!");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar: Paquete no encontrado.");
        }
    }//GEN-LAST:event_btnGuardarDetallesActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDetallePaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDetallePaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDetallePaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDetallePaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDetallePaquete(new gestion.GestionPaquete()).setVisible(true);}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPaquete;
    private javax.swing.JButton btnGuardarDetalles;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoPaquete;
    private javax.swing.JLabel lblItinerario;
    private javax.swing.JLabel lblServicios1;
    private javax.swing.JTextField txtCodigoPaquete;
    private javax.swing.JTextArea txtItinerario;
    private javax.swing.JTextArea txtServicios;
    // End of variables declaration//GEN-END:variables
}
