/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Clases.Reserva;
import Clases.PaqueteTuristico;
import Clases.Cliente;
import gestion.GestionReserva;
import gestion.GestionPaquete;
import gestion.GestionCliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CRISTOPHER
 */
public class frmRegistroReserva extends javax.swing.JFrame {
    
    private DefaultTableModel modeloReservas;
    private DefaultTableModel modeloPasajeros;
    private GestionReserva gestionReserva;
    private GestionPaquete gestionPaquete;
    private GestionCliente gestionCliente;
    
    /**
     * Creates new form frmRegistroReserva
     */
    public frmRegistroReserva() {
        initComponents();
        inicializarTablas();
    }

    public frmRegistroReserva(GestionReserva gestionReserva, GestionPaquete gestionPaquete, GestionCliente gestionCliente) {
        initComponents();
        this.gestionReserva = gestionReserva;
        this.gestionPaquete = gestionPaquete;
        this.gestionCliente = gestionCliente;
        
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        inicializarTablas();
        listarReservas();
    }

    private void inicializarTablas() {
        modeloReservas = new DefaultTableModel();
        modeloReservas.addColumn("Código");
        modeloReservas.addColumn("Paquete");
        modeloReservas.addColumn("Adultos");
        modeloReservas.addColumn("Menores");
        modeloReservas.addColumn("Precio Total");
        modeloReservas.addColumn("Estado");
        tbReservas.setModel(modeloReservas);

        modeloPasajeros = new DefaultTableModel();
        modeloPasajeros.addColumn("DNI/Pasaporte");
        modeloPasajeros.addColumn("Nombres");
        modeloPasajeros.addColumn("Apellidos");
        modeloPasajeros.addColumn("Nacionalidad");
        tbPasajerosGrupo.setModel(modeloPasajeros);
    }

    void listarReservas() {
        modeloReservas.setNumRows(0);
        for (int i = 0; i < gestionReserva.obtenerTotalReservas(); i++) {
            Reserva res = gestionReserva.obtenerReserva(i);
            Object[] fila = new Object[6];
            fila[0] = res.getCodigoReserva();
            fila[1] = (res.getPaquete() != null) ? res.getPaquete().getNombre() : "N/A";
            fila[2] = res.getPasajerosAdultos();
            fila[3] = res.getPasajerosMenores();
            fila[4] = res.getPrecioTotal();
            fila[5] = res.getEstadoReserva();
            modeloReservas.addRow(fila);
        }
    }

    private void limpiarCampos() {
        txtCodigoReserva.setText("");
        txtCodigoPaquete.setText("");
        txtAdultos.setText("");
        txtMenores.setText("");
        txtDniPasajero.setText("");
        txtCodigoReserva.requestFocus();
    }
    
    void listarPasajerosDeReserva(Reserva res) {
        modeloPasajeros.setNumRows(0);
        for (int i = 0; i < res.getTotalClientes(); i++) {
            Cliente c = res.getClientes()[i];
            if (c != null) {
                Object[] fila = new Object[4];
                fila[0] = c.getDNI();
                fila[1] = c.getNombres();
                fila[2] = c.getApellidos();
                fila[3] = c.getNacionalidad();
                modeloPasajeros.addRow(fila);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        txtCodigoReserva = new javax.swing.JTextField();
        lblCodigoReserva = new javax.swing.JLabel();
        txtCodigoPaquete = new javax.swing.JTextField();
        lblCodigoPaquete = new javax.swing.JLabel();
        txtAdultos = new javax.swing.JTextField();
        lblAdultos = new javax.swing.JLabel();
        txtMenores = new javax.swing.JTextField();
        lblMenores = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReservas = new javax.swing.JTable();
        txtDescuentoMenores = new javax.swing.JTextField();
        lblDescuentoMenores = new javax.swing.JLabel();
        txtDniPasajero = new javax.swing.JTextField();
        lblDniPasajero = new javax.swing.JLabel();
        btnAsociarPasajero = new javax.swing.JButton();
        btnBuscarReservaPasajeros = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPasajerosGrupo = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCodigoReserva.setText("Codigo Reserva");

        lblCodigoPaquete.setText("Codigo Paquete");

        lblAdultos.setText("Pasajeros Adultos");

        lblMenores.setText("Pasajaros Menores");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tbReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbReservas);

        txtDescuentoMenores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoMenoresActionPerformed(evt);
            }
        });

        lblDescuentoMenores.setText("Descuento Menores");

        lblDniPasajero.setText("Dni Pasajero");

        btnAsociarPasajero.setText("Asociar Pasajero");
        btnAsociarPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarPasajeroActionPerformed(evt);
            }
        });

        btnBuscarReservaPasajeros.setText("Buscar Reserva Pasajeros");
        btnBuscarReservaPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservaPasajerosActionPerformed(evt);
            }
        });

        tbPasajerosGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbPasajerosGrupo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoReserva)
                            .addComponent(txtCodigoPaquete)
                            .addComponent(txtAdultos)
                            .addComponent(txtMenores)
                            .addComponent(txtDescuentoMenores)
                            .addComponent(txtDniPasajero))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoReserva)
                            .addComponent(lblCodigoPaquete)
                            .addComponent(lblAdultos)
                            .addComponent(lblMenores)
                            .addComponent(lblDescuentoMenores)
                            .addComponent(lblDniPasajero))
                        .addGap(225, 225, 225))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAsociarPasajero)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarReservaPasajeros)))
                        .addGap(11, 11, 11))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoPaquete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMenores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescuentoMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescuentoMenores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDniPasajero))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnAsociarPasajero)
                    .addComponent(btnBuscarReservaPasajeros))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String codigoReserva = txtCodigoReserva.getText().trim();
    String codigoPaquete = txtCodigoPaquete.getText().trim();
    
    if (codigoReserva.isEmpty() || codigoPaquete.isEmpty() || txtAdultos.getText().isEmpty() || txtMenores.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        return;
    }

    PaqueteTuristico paqueteElegido = gestionPaquete.buscarPorCodigo(codigoPaquete);
    if (paqueteElegido == null) {
        JOptionPane.showMessageDialog(this, "Error: El código de paquete ingresado no existe.");
        return;
    }

    int pasajerosAdultos = Integer.parseInt(txtAdultos.getText().trim());
    int pasajerosMenores = Integer.parseInt(txtMenores.getText().trim());
    double descMenores = Double.parseDouble(txtDescuentoMenores.getText().trim());

    Reserva nuevaReserva = new Reserva(codigoReserva, paqueteElegido, pasajerosAdultos, pasajerosMenores, descMenores);

    if (!nuevaReserva.registro()) {
        JOptionPane.showMessageDialog(this, "No se puede registrar: El paquete no cuenta con cupos suficientes.", "Sin Cupo", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (gestionReserva.registrar(nuevaReserva)) {
        JOptionPane.showMessageDialog(this, "Reserva registrada con éxito. Estado: " + nuevaReserva.getEstadoReserva());
        listarReservas();
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "Error: El código de reserva ya se encuentra registrado.");
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarReservaPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservaPasajerosActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoReserva.getText().trim();
    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el código de la reserva.");
        return;
    }

    Reserva res = gestionReserva.buscarPorCodigo(codigo);
    if (res != null) {
        listarPasajerosDeReserva(res);
        JOptionPane.showMessageDialog(this, "Reserva cargada. Pasajeros actuales en el grupo: " + res.getTotalClientes());
    } else {
        JOptionPane.showMessageDialog(this, "Reserva no encontrada.");
    }
    }//GEN-LAST:event_btnBuscarReservaPasajerosActionPerformed

    private void btnAsociarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarPasajeroActionPerformed
        // TODO add your handling code here:
        String codigoReserva = txtCodigoReserva.getText().trim();
        String dniPasajero = txtDniPasajero.getText().trim();

        if (codigoReserva.isEmpty() || dniPasajero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Especifique el Código de Reserva y el DNI del Pasajero.");
            return;
        }

        Reserva res = gestionReserva.buscarPorCodigo(codigoReserva);
        if (res == null) {
            JOptionPane.showMessageDialog(this, "La reserva especificada no existe.");
            return;
        }

        Cliente clienteEncontrado = gestionCliente.buscarPorDni(dniPasajero);
        if (clienteEncontrado == null) {
            JOptionPane.showMessageDialog(this, "El cliente con DNI " + dniPasajero + " no está registrado en el sistema.\nPor favor, regístrelo primero en el Mantenimiento de Clientes.");
            return;
        }

        if (res.agregarClientes(clienteEncontrado)) {
            JOptionPane.showMessageDialog(this, "¡Pasajero " + clienteEncontrado.getNombres() + " asociado con éxito al grupo!");
            listarPasajerosDeReserva(res);
            txtDniPasajero.setText("");
            txtDniPasajero.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar: Se ha alcanzado el límite máximo de pasajeros calculados para esta reserva.");
        }
    }//GEN-LAST:event_btnAsociarPasajeroActionPerformed

    private void txtDescuentoMenoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoMenoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoMenoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroReserva(
                    new gestion.GestionReserva(), 
                    new gestion.GestionPaquete(), 
                    new gestion.GestionCliente()
                ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsociarPasajero;
    private javax.swing.JButton btnBuscarReservaPasajeros;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAdultos;
    private javax.swing.JLabel lblCodigoPaquete;
    private javax.swing.JLabel lblCodigoReserva;
    private javax.swing.JLabel lblDescuentoMenores;
    private javax.swing.JLabel lblDniPasajero;
    private javax.swing.JLabel lblMenores;
    private javax.swing.JTable tbPasajerosGrupo;
    private javax.swing.JTable tbReservas;
    private javax.swing.JTextField txtAdultos;
    private javax.swing.JTextField txtCodigoPaquete;
    private javax.swing.JTextField txtCodigoReserva;
    private javax.swing.JTextField txtDescuentoMenores;
    private javax.swing.JTextField txtDniPasajero;
    private javax.swing.JTextField txtMenores;
    // End of variables declaration//GEN-END:variables
}
